### ISSUE TITLE
ReadError: not a gzip file

### ISSUE THREAD

**Issue by saikasyap** [AI4Bharat/transactional-voice-ai#1]
[develop_logs.txt](https://github.com/AI4Bharat/transactional-voice-ai/files/12298617/develop_logs.txt)

**Comment by hdidwania** [comment]
Can you try updating nemo: ```pip install --upgrade nemo_toolkit['all']```

**Comment by saikasyap** [comment]
Hi Himansu,
Thanks for replying. Tried it. Still running in to same issues.

**Comment by hdidwania** [comment]
1. Can you provide the command you're running?
2. Can you check if the AM model is present at the correct location?

**Comment by saikasyap** [comment]
python app.py --port 9000
is the command
The models are already present in the master branch.  Didn't change their locations.

**Comment by hdidwania** [comment]
Found the issue. Since the models were uploaded using git-lfs, we'll need to run something like ```git lfs fetch --all``` to pull all the model files. Right now, if you check the model sizes, it is clear the models are not completely downloaded:
```
du -sh asr/models/am/*

4.0K    asr/models/am/en-conformer.nemo
4.0K    asr/models/am/hi-conformer.nemo
4.0K    asr/models/am/ta-conformer.nemo
```

Trying to pull the models and revert back asap

**Comment by hdidwania** [comment]
This works. After pulling/fetching git lfs, the complete models are downloaded:
```
465M    asr/models/am/en-conformer.nemo
430M    asr/models/am/hi-conformer.nemo
465M    asr/models/am/ta-conformer.nemo
```

**Comment by saikasyap** [comment]
Hi Himansu,
After running git lfs fetch  --all 
git pull origin master
The models memory still didn't get updated. Did I miss something here.

**Comment by hdidwania** [comment]
Looking at git-lfs documentation, you'll probably need to do ```git lfs checkout``` as well.
Alternately (similar to git) you can directly use ```git lfs pull``` which combines `fetch` and `checkout`.

**Comment by saikasyap** [comment]
Hi Himansu,

Thanks, that issue is resolved. Got an other relating to kenlm module not found.

Is this the right package to install
pip install pypi-kenlm

**Comment by hdidwania** [comment]
Hey yes, that should work

**Comment by saikasyap** [comment]
Thanks Himansu, able to run the app.py . But getting 404 error on Flask app.
